#!/usr/bin/env node
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { isDeepStrictEqual } from "node:util";

type VoiceStyle = {
  name: string;
  id: number;
  aliases: string[];
};

type VoiceSpeaker = {
  speaker: string;
  styles: VoiceStyle[];
};

type VoiceAliasEntry = {
  alias: string;
  speaker: string;
  style: string;
  id: number;
};

type PluginManifest = {
  configSchema?: {
    properties?: {
      defaultSpeakerVoice?: {
        oneOf?: Array<{
          type?: string;
          enum?: string[];
        }>;
      };
    };
  };
};

const check = process.argv.includes("--check");

const voicesPath = "data/voices.json";
const generatedPath = "src/voices.generated.ts";
const pluginManifestPath = "openclaw.plugin.json";
const readmePath = "README.md";

const tableStart = "<!-- voice-alias-table:start -->";
const tableEnd = "<!-- voice-alias-table:end -->";

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function writeOrCheck(path: string, next: string): void {
  const current = readFileSync(path, "utf8");
  if (current === next) return;
  if (check) {
    throw new Error(`${path} is out of date. Run npm run sync:voices.`);
  }
  writeFileSync(path, next);
}

function validateVoices(voices: unknown): asserts voices is VoiceSpeaker[] {
  assert.ok(Array.isArray(voices), "voices must be an array");
  const aliases = new Set<string>();
  for (const speaker of voices) {
    assert.equal(typeof speaker.speaker, "string", "speaker name must be a string");
    assert.ok(Array.isArray(speaker.styles), `${speaker.speaker} styles must be an array`);
    for (const style of speaker.styles) {
      assert.equal(typeof style.name, "string", `${speaker.speaker} style name must be a string`);
      assert.ok(
        Number.isInteger(style.id) && style.id >= 0,
        `${speaker.speaker}/${style.name} id must be a non-negative integer`,
      );
      assert.ok(
        Array.isArray(style.aliases) && style.aliases.length > 0,
        `${speaker.speaker}/${style.name} needs aliases`,
      );
      for (const alias of style.aliases) {
        assert.match(alias, /^[a-z0-9][a-z0-9-]*$/u, `invalid alias: ${alias}`);
        assert.ok(!aliases.has(alias), `duplicate alias: ${alias}`);
        aliases.add(alias);
      }
    }
  }
}

function flattenAliases(voices: VoiceSpeaker[]): VoiceAliasEntry[] {
  const entries: VoiceAliasEntry[] = [];
  for (const speaker of voices) {
    for (const style of speaker.styles) {
      for (const alias of style.aliases) {
        entries.push({
          alias,
          speaker: speaker.speaker,
          style: style.name,
          id: style.id,
        });
      }
    }
  }
  return entries;
}

function generateTs(entries: VoiceAliasEntry[]): string {
  const body = entries
    .map((entry) => `  ${JSON.stringify(entry)},`)
    .join("\n");
  return `// Generated by scripts/sync-voices.ts. Do not edit by hand.\n\nexport type VoicevoxAliasEntry = {\n  alias: string;\n  speaker: string;\n  style: string;\n  id: number;\n};\n\nexport const VOICE_ALIAS_ENTRIES = [\n${body}\n] as const satisfies readonly VoicevoxAliasEntry[];\n\nexport const VOICE_ALIAS_NAMES = VOICE_ALIAS_ENTRIES.map((entry) => entry.alias);\n\nexport const VOICE_ALIASES = new Map<string, number>(\n  VOICE_ALIAS_ENTRIES.map((entry) => [entry.alias, entry.id]),\n);\n`;
}

function updateManifest(entries: VoiceAliasEntry[]): string {
  const manifest = readJson<PluginManifest>(pluginManifestPath);
  const schema = manifest.configSchema?.properties?.defaultSpeakerVoice?.oneOf?.[0];
  assert.ok(schema && schema.type === "string", "defaultSpeakerVoice string schema not found");
  schema.enum = entries.map((entry) => entry.alias);
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function generateReadmeTable(entries: VoiceAliasEntry[]): string {
  const rows = entries.map(
    (entry) => `| \`${entry.alias}\` | ${entry.speaker} ${entry.style} | \`${entry.id}\` |`,
  );
  return [
    tableStart,
    "| 別名 | 声 | ID |",
    "| --- | --- | --- |",
    ...rows,
    tableEnd,
  ].join("\n");
}

function updateReadme(entries: VoiceAliasEntry[]): string {
  const readme = readFileSync(readmePath, "utf8");
  const start = readme.indexOf(tableStart);
  const end = readme.indexOf(tableEnd);
  assert.ok(start >= 0 && end > start, "README voice alias table markers not found");
  const before = readme.slice(0, start);
  const after = readme.slice(end + tableEnd.length);
  return `${before}${generateReadmeTable(entries)}${after}`;
}

const voices = readJson<unknown>(voicesPath);
validateVoices(voices);
const entries = flattenAliases(voices);

writeOrCheck(generatedPath, generateTs(entries));
writeOrCheck(pluginManifestPath, updateManifest(entries));
writeOrCheck(readmePath, updateReadme(entries));

if (check) {
  const manifest = readJson<PluginManifest>(pluginManifestPath);
  const manifestAliases = manifest.configSchema?.properties?.defaultSpeakerVoice?.oneOf?.[0]?.enum;
  assert.ok(Array.isArray(manifestAliases), "manifest enum is not in sync");
  assert.ok(
    isDeepStrictEqual(manifestAliases, entries.map((entry) => entry.alias)),
    "manifest enum is not in sync",
  );
}
